/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#define ENTITYCLASS CGhostBusterRay

CEntityProperty CGhostBusterRay_properties[] = {
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000001f9<<8)+1, _offsetof(CGhostBusterRay, m_penOwner), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_BOOL, NULL, (0x000001f9<<8)+2, _offsetof(CGhostBusterRay, m_bRender), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x000001f9<<8)+3, _offsetof(CGhostBusterRay, m_vSrcOld), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x000001f9<<8)+4, _offsetof(CGhostBusterRay, m_vDstOld), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x000001f9<<8)+5, _offsetof(CGhostBusterRay, m_vSrc), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x000001f9<<8)+6, _offsetof(CGhostBusterRay, m_vDst), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_FLOAT3D, NULL, (0x000001f9<<8)+10, _offsetof(CGhostBusterRay, m_iLastBulletPosition), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ANIMOBJECT, NULL, (0x000001f9<<8)+11, _offsetof(CGhostBusterRay, m_aoLightAnim), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_INDEX, NULL, (0x000001f9<<8)+12, _offsetof(CGhostBusterRay, m_ctPasses), "", 0, 0, 0),
 CEntityProperty(CEntityProperty::EPT_ENTITYPTR, NULL, (0x000001f9<<8)+255, _offsetof(CGhostBusterRay, m_penPrediction), "", 0, 0, 0),
};
#define CGhostBusterRay_propertiesct ARRAYCOUNT(CGhostBusterRay_properties)

CEntityComponent CGhostBusterRay_components[] = {
#define CLASS_LIGHT ((0x000001f9<<8)+1)
 CEntityComponent(ECT_CLASS, CLASS_LIGHT, "EFNM" "Classes\\Light.ecl"),
#define CLASS_BULLET ((0x000001f9<<8)+2)
 CEntityComponent(ECT_CLASS, CLASS_BULLET, "EFNM" "Classes\\Bullet.ecl"),
#define MODEL_RAY ((0x000001f9<<8)+10)
 CEntityComponent(ECT_MODEL, MODEL_RAY, "EFNM" "Models\\Weapons\\GhostBuster\\Projectile\\Ray.mdl"),
#define TEXTURE_RAY ((0x000001f9<<8)+11)
 CEntityComponent(ECT_TEXTURE, TEXTURE_RAY, "EFNM" "Models\\Weapons\\GhostBuster\\Projectile\\Ray.tex"),
};
#define CGhostBusterRay_componentsct ARRAYCOUNT(CGhostBusterRay_components)

CEventHandlerEntry CGhostBusterRay_handlers[] = {
 {1, -1, CEntity::pEventHandler(&CGhostBusterRay::
#line 201 "/home/seb/git/Serious-Seb/Sources/Entities/GhostBusterRay.es"
Main),DEBUGSTRING("CGhostBusterRay::Main")},
};
#define CGhostBusterRay_handlersct ARRAYCOUNT(CGhostBusterRay_handlers)

CEntity *CGhostBusterRay_New(void) { return new CGhostBusterRay; };
void CGhostBusterRay_OnInitClass(void) {};
void CGhostBusterRay_OnEndClass(void) {};
void CGhostBusterRay_OnPrecache(CDLLEntityClass *pdec, INDEX iUser);
void CGhostBusterRay_OnWorldEnd(CWorld *pwo) {};
void CGhostBusterRay_OnWorldInit(CWorld *pwo) {};
void CGhostBusterRay_OnWorldTick(CWorld *pwo) {};
void CGhostBusterRay_OnWorldRender(CWorld *pwo) {};
ENTITY_CLASSDEFINITION(CGhostBusterRay, CMovableModelEntity, "GhostBusterRay", "", 0x000001f9);
DECLARE_CTFILENAME(_fnmCGhostBusterRay_tbn, "");
